### PR TITLE
fix: ruby element reference query

### LINKED ISSUE #1005: Multiple results returned for query error
## Description & Reproduction

Scan the following code

```ruby
def bug
  foo = [:a, :b, :c, :d, :e]
  logger.info(foo[0,2].join(":"))

  logger.info(current_user.email) # should be found
end
```

## Expected Behavior

The scan reports the findings (open redirect, sensitive data in log)

## Actual Behavior

No findings are reported

## Possible Fix

Running detectors report yields the following error: 

```
failed to process file for detector : ruby failed to detect in file example.rb: query returned more than one result
```

## Your Environment

- Operating System and version:
- Output of 'bearer version':
```
bearer version: main
sha: 814937fa9c00701facfdcedc911615d1047cb3ea
```

### PR DESCRIPTION
**Pull request by elsapet**
## Description

Our element reference query was matching on things like `foo_array[0, 2]`. This was causing issue with the pattern matching returning multiple results. 
To address this, we add some anchors to the query so that we now match only on the simple hash access case e.g. `foo[:bar]`.

Closes #1005 

## Checklist

- [ ] I've added test coverage that shows my fix or feature works as expected.
- [ ] I've updated or added documentation if required.
- [ ] I've included usage information in the description if CLI behavior was updated or added.
- [ ] PR title follows [Conventional Commits](https://www.conventionalcommits.org/) format

### CODE REVIEW

**Review by didroe — APPROVED** [review]
You could add a multiple index case here:
https://github.com/Bearer/bearer/blob/main/new/detector/implementation/ruby/testdata/object_projection.rb

File: new/detector/composition/ruby/ruby.go [hunk 1]
```diff
@@ -192,10 +192,14 @@ func (composition *Composition) DetectFromFileWithTypes(file *file.FileInfo, det
...
+		sanitizerRuleID := ""
+		if rule != nil {
+			sanitizerRuleID = rule.SanitizerRuleID
+		}
 		detections, err := evaluator.Evaluate(
 			tree.RootNode(),
 			detectorType,
-			rule.SanitizerRuleID,
+			sanitizerRuleID,
 			settings.NESTED_SCOPE,
```
Comment (elsapet) [inline new/detector/composition/ruby/ruby.go:203]: I'll re-visit this tomorrow - @didroe I'm guessing a `nil` rule here is not a real-world possibility?

Comment (didroe) [reply new/detector/composition/ruby/ruby.go:203]: You should always have a rule as the `detectorTypes` were gathered from the rules in the first place

Comment (elsapet) [reply new/detector/composition/ruby/ruby.go:203]: ^ From discussion with @didroe : some built-in detectors e.g. `datatype` won't have a rule so we are okay to handle the `nil` case here (it's not just for the tests)
