### PR TITLE
fix: rule caching and language support

### LINKED ISSUE #914: Rules are always downloaded if repo contains non-rule-supported file types (HTML, CSS, txt)
## Description & Reproduction

We are always refreshing the rules and never relying on the cached version. This is a result of the fix here: https://github.com/Bearer/bearer/pull/904

Found languages can include a variety e.g. CSS, HTML, plain text and as such the logic for the above fix is too naïve. We need to ask if we have rules for the found language. 

## Repro steps

1. Scan a repository that has a variety of file types e.g. `.rb`, `.txt`, `.html`
2. Re-scan the same repository

## Expected Behavior

On the re-scan we should be using cached rules

## Actual Behavior

We download the rules every time

## Possible Fix

Could possibly update the [`anySupportedLanguagesPresent` method](https://github.com/Bearer/bearer/blob/main/pkg/commands/artifact/run.go#L392) to return the found and supported languages, and use this in rules cache process

## Your Environment

- Operating System and version: running locally 
- Output of 'bearer version':
```
bearer version: dev / 
sha: cad5fcdecf81921f2776641c19de558a844a0d7f
```

### PR DESCRIPTION
**Pull request by elsapet**
## Description

* Extract support languages to rules file
* Fix logic in rules caching - check found language has rule support before we re-download the rules 🙈 

Closes #914

## Checklist

- [ ] I've added test coverage that shows my fix or feature works as expected.
- [ ] I've updated or added documentation if required.
- [ ] I've included usage information in the description if CLI behavior was updated or added.
- [ ] PR title follows [Conventional Commits](https://www.conventionalcommits.org/) format

### CODE REVIEW

File: pkg/commands/process/settings/rules.go [hunk 1]
```diff
@@ -17,6 +17,14 @@ var (
 	defaultAuxiliaryRuleType = "verifier"
 )
 
+func GetSupportedRuleLanguages() map[string]bool {
+	return map[string]bool{
+		"ruby":       true,
+		"javascript": true,
+		"typescript": true,
+	}
+}
```
Comment (elsapet) [inline pkg/commands/process/settings/rules.go:26]: Hard coding this for speed: I'm wanting to know which languages have rule support without doing any API calls e.g. to get the folder names from bearer-rules. 

Not sure this solution is ideal - am open to suggestions 🙏

**Review by didroe — APPROVED** [review]
