### PR TITLE
test: make e2e snapshots consistent

### LINKED ISSUE #1039: Tests fail locally for parallel flag default
## Description & Reproduction
when running tests locally parallel flag default changes compared to CI environment
```Diff
-      --parallel int                         Specify the amount of parallelism to use during the scan (default 2)
+      --parallel int                         Specify the amount of parallelism to use during the scan (default 4)
```

### PR DESCRIPTION
**Pull request by didroe**
## Description

Make E2E test snapshots consistent locally and in CI, and with or without the binary:
- Override default parallel value, making it independent of the number of CPUs in the environment
- Strip the "exit status 1" text that `go run` adds

## Related
- Close #1039 

## Checklist

- [ ] I've added test coverage that shows my fix or feature works as expected.
- [ ] I've updated or added documentation if required.
- [ ] I've included usage information in the description if CLI behavior was updated or added.
- [x] PR title follows [Conventional Commits](https://www.conventionalcommits.org/) format

### CODE REVIEW

File: e2e/internal/testhelper/testhelper.go [hunk 1]
```diff
@@ -51,7 +51,10 @@ func executeApp(t *testing.T, arguments []string) (string, error) {
 
 	timer := time.NewTimer(TestTimeout)
 	commandFinished := make(chan struct{}, 1)
-	combinedOutput := func() string { return buffOut.String() + "\n--\n" + buffErr.String() }
+	combinedOutput := func() string {
+		errStr := strings.TrimSuffix(buffErr.String(), "exit status 1\n")
+		return buffOut.String() + "\n--\n" + errStr
+	}
```
Comment (elsapet) [inline e2e/internal/testhelper/testhelper.go:57]: 🙌

**Review by elsapet — APPROVED** [review]

**Review by gotbadger — APPROVED** [review]
