### PR TITLE
Fix: empty dir and browserlistrc

### LINKED ISSUE #399: CR-025 .browserslistrc false positive
## Description

`.browserslistrc` is a fairly common file used to indicate [supported browsers](https://github.com/browserslist/browserslist) in a webapp

## Expected Behavior

Should not trigger CR-025

## Actual Behavior

```
CRITICAL: Do not leak secrets. [CR-025]
https://curio.sh/reference/policies/#CR-025

Detected: Sensitive file name
File: .../.browserslistrc:1
```

file had the following content
```
defaults
```

## Possible Fix

ignore this file

## Steps to Reproduce

1. create a file called .browserslistrc
2. run curio scan

## Your Environment

- Version used:  0.22.0
- Target codebase stack (e.g. Ruby): Ruby

### LINKED ISSUE #413: Error when scanning empty directory
## Description

When scanning an empty directory an error is generated this is due to trying to construct a progress bar for 0 items

## Expected Behavior

Warning about no files found or nothing

## Actual Behavior

```
{"level":"error","time":"2023-01-18T17:07:00Z","message":"worker 115fd34d-7b0d-4d5e-be6a-0ff4f4855161 failed to write progress bar &{%!e(string=max must be greater than 0)}"}
```

## Possible Fix

Dont generate bar if no files

## Steps to Reproduce
```
$ mkdir empty 
$ ./curio scan ./empty                                                                                                                                        
Scanning target ./empty
{"level":"error","time":"2023-01-18T17:07:00Z","message":"worker 115fd34d-7b0d-4d5e-be6a-0ff4f4855161 failed to write progress bar &{%!e(string=max must be greater than 0)}"}
Running Detectors
Generating dataflow

The policy report is not yet available for your stack. Learn more at https://curio.sh/explanations/reports/

Run the data flow report if you want the full output using: curio scan ./empty --report dataflow
```

## Your Environment

- Version used:
- Target codebase stack (e.g. Ruby):
- Operating System and version:
- Link to your project or code sample:

### PR DESCRIPTION
**Pull request by vjerci**
## Description
This pr fixes empty directory error:
```
$ go run ./cmd/curio/main.go scan ../empty-dir --force
directory empty: we couldn't find any files to scan in specified directory
```
When directory is empty we exit with status 0, I've figured there is no real error but user still needs a warning message.

This pr also fixes .browserlistrc sensitive file detection
We had some complicated regex there detecting sensitive files and `trc` (comes from trace) was being detected there as sensitive, I've changed it to detect only `.trc` file

## Related
- closes https://github.com/Bearer/curio/issues/399
- closes https://github.com/Bearer/curio/issues/413

## Checklist

- [ ] I've added test coverage that shows my fix or feature works as expected.
- [ ] I've updated or added documentation if required.
- [ ] I've included usage information in the description if CLI behavior was updated or added.
- [ ] PR title follows [Conventional Commits](https://www.conventionalcommits.org/) format

### CODE REVIEW

**Review by cfabianski — APPROVED** [review]

**Comment by cfabianski** [comment]
Could you rebase (or update base) please?

File: pkg/commands/process/balancer/worker.go [hunk 1]
```diff
@@ -21,6 +21,8 @@ import (
 	"github.com/bearer/curio/pkg/util/tmpfile"
 )
 
+var ErrFileListEmpty = errors.New("we couldn't find any files to scan in specified directory")
```
Comment (markmichon) [inline pkg/commands/process/balancer/worker.go]:
```suggestion
var ErrFileListEmpty = errors.New("We couldn't find any files to scan in the specified directory.")
```

**Review by markmichon — CHANGES_REQUESTED** [review]
lgtm. Left one small copy suggestion
